---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Session-Store-FastMmap
no_index:
  directory:
    - t
    - inc
requires:
  Cache::FastMmap: 1.29
  Catalyst::ClassData: 0
  Catalyst::Plugin::Session: 0.27
  Catalyst::Runtime: 5.8
  File::Spec: 0
  File::Temp: 0
  MRO::Compat: 0
  MooseX::Emulate::Class::Accessor::Fast: 0
  Path::Class: 0
version: 0.16
