--- #YAML:1.0
name:                Catalyst-Plugin-Session-Store-FastMmap
version:             0.05
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Cache::FastMmap:               1.13
    Catalyst::Plugin::Session:     0.09
    File::Spec:                    0
    File::Temp:                    0
    Path::Class:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
