--- #YAML:1.0
name:               Catalyst-Plugin-Session-Store-FastMmap
version:            0.15
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::FastMmap:      1.29
    Catalyst::ClassData:  0
    Catalyst::Plugin::Session:  0.27
    Catalyst::Runtime:    5.8
    File::Spec:           0
    File::Temp:           0
    MooseX::Emulate::Class::Accessor::Fast:  0
    MRO::Compat:          0
    Path::Class:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
